-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 21, 2025 at 04:57 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `thepagelibrary`
--

-- --------------------------------------------------------

--
-- Table structure for table `books`
--

CREATE TABLE `books` (
  `book_id` int(11) NOT NULL,
  `book_name` varchar(100) NOT NULL,
  `book_author` varchar(200) NOT NULL,
  `author_img` varchar(200) NOT NULL,
  `book_description` mediumtext NOT NULL,
  `Book_Img` varchar(255) NOT NULL,
  `book_price` int(11) NOT NULL,
  `book_pages` int(11) NOT NULL,
  `genre` varchar(255) DEFAULT NULL,
  `category` varchar(100) NOT NULL,
  `selling` varchar(50) NOT NULL,
  `date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `Status` varchar(100) NOT NULL,
  `author_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `books`
--

INSERT INTO `books` (`book_id`, `book_name`, `book_author`, `author_img`, `book_description`, `Book_Img`, `book_price`, `book_pages`, `genre`, `category`, `selling`, `date`, `Status`, `author_id`) VALUES
(2, 'Lords of Creation', 'Adrian Tchaikovsky', 'adrian.jpg', 'Children of Memory is a 2023 science fiction novel by author Adrian Tchaikovsky. The novel follows the development of a mysterious colony on a hostile exoplanet, while the human civilization from the previous books encounters a society of intelligent corvids.', 'lordsofuncreation.jpg', 365, 499, 'science fiction', 'fiction', '', '2025-02-03 07:40:34', 'true', NULL),
(3, 'The Fury', 'Alex Michaelides', 'alex.jpg', 'A masterfully paced thriller about a reclusive ex–movie star and her famous friends whose spontaneous trip to a private Greek island is upended by a murder ― from the #1 New York Times bestselling author of The Silent Patient. This is a tale of murder.', 'thefury.jpg', 350, 278, 'mystery', 'fiction', '', '2025-02-02 07:22:00', 'true', NULL),
(4, 'The Silent Patient', 'Alex Michaelides', 'alex.jpg', 'English psychotherapist, Theo Faber, dealing with a patient who turns mute after murdering her husband. Upon its release, the book debuted on The New York Times Best Seller list at No. 1.', 'sp.jpg', 250, 299, 'mystery', 'fiction', 'best', '2025-02-02 07:22:16', 'true', NULL),
(5, 'The Maidens', 'Alex Michaelides ', 'alex.jpg', 'That said, Michaelides has once again woven a tight, compelling thriller with a twisty pay-off. This one follows Mariana, a psychologist and recent widow, who races to Cambridge when her niece calls with news that a fellow Oxford student has been brutally murdered.', 'themaidens.jpg', 200, 368, 'mystery', 'fiction', '', '2025-02-03 05:24:55', 'true', NULL),
(6, 'Love on the Brain', 'Ali Hazelwood', 'ali.jpeg', 'Quirky girl in STEM academia (graduated this time) meets very large, dark-haired, broody guy who is unable to communicate the fact that he\'s been in love with her for years. He defends her career, swoops to her rescue when needed, yet she cannot fathom why he\'d want to be around her.', 'loveonthebrain.jpg', 279, 383, 'romance', 'fiction', '', '2025-02-02 07:22:39', 'true', NULL),
(7, 'Not in Love', 'Ali Hazelwood', 'ali.jpg', 'The story follows Rue Siebert, a food scientist working for a biotech firm that is at risk of being bought out by a venture capitalist firm run by four business partners, one of whom is Eli Killgore, the man she met on a dating app and very nearly hooked up with.', 'notinlove.jpg', 500, 379, 'romance', 'fiction', '', '2025-02-03 05:33:20', 'true', NULL),
(8, 'Under One Roof', 'Ali Hazelwood', 'ali.jpg', 'Mara, Sadie, and Hannah are friends first, scientists always. Though their fields of study might take them to different corners of the world, they can all agree on this universal truth: when it comes to love and science, opposites attract and rivals make you burn...\r\n\r\nAs an environmental engineer, Mara knows all about the delicate nature of ecosystems. They require balance. And leaving the thermostat alone. And not stealing someone else\'s food. And other rules Liam, her detestable big-oil lawyer of a roommate, knows nothing about. Okay, sure, technically she\'s the interloper. Liam was already entrenched in his aunt\'s house like some glowering grumpy giant when Mara moved in, with his big muscles and kissable mouth just sitting there on the couch tempting respectable scientists to the dark side...but Helena was her mentor and Mara\'s not about to move out and give up her inheritance without a fight.\r\n\r\nThe problem is, living with someone means getting to know them. And the more Mara finds out about Liam, the harder it is to loathe him...and the easier it is to love him.', 'underoneroof.jpg', 277, 150, 'romance', 'fiction', 'best', '2025-02-03 07:29:05', 'true', NULL),
(9, 'Ram Scion of Ikshvaku', 'Amish Tripathi', 'amishtripathi.jpg', 'The story begins with King Dashrath of Ayodhya being defeated in a war by Lankan trader Raavan, and the birth of his son Ram. It follows through Ram\'s childhood and tutelage, along with the politics surrounding his ascension to the throne, and ultimately his 14-year exile, accompanied by wife Sita and brother Lakshman.', 'ram.jpg', 300, 354, 'ya', 'fiction', 'best', '2025-02-02 11:06:38', 'true', NULL),
(10, 'Sita: Warrior of Mithila ', 'Amish Tripathi', 'amish.jpg', 'Sita: Warrior of Mithila is the fifth book of Amish Tripathi, fifth book of Amishverse, and second book of Ram Chandra Series. It was released on 29 May 2017. Ram Chandra Series is a retelling of the most famous epic of India, the Ramayana. Each book in the series focuses on one important character of the Ramayana.', 'sita.jpg', 400, 360, 'fantasy', 'fiction', '', '2025-02-03 05:29:08', 'true', NULL),
(11, 'Ravan: Enemy of Aryavarta', 'Amish Tripathi', 'amish.jpg', 'Raavan: Enemy of Aryavarta is the seventh book of Amish Tripathi, sixth book of Amishverse, and third book of Ram Chandra Series. It chronicles the life of Ravan until the time he kidnaps Sita. The book was released on 1 July 2019 and published by Westland.', 'raavan.jpg', 300, 400, 'fantasy', 'fiction', '', '2025-02-03 05:31:28', 'true', NULL),
(12, 'Twisted Games', 'Ana Huang', 'anahuang.jpg', 'Regal, strong-willed, and bound by the chains of duty, Princess Bridget dreams of the freedom to live and love as she chooses. But when her brother abdicates, she\'s suddenly faced with the prospect of a loveless, politically expedient marriage and a throne she never wanted.', 'tg.jpg', 299, 480, 'romance ', 'fiction', 'best', '2025-02-02 07:23:10', 'true', NULL),
(13, 'The Striker', 'Ana Huang', 'anahuang.jpg', 'Based on the Premier League in England, the novel follows a male footballer, Asher Donovan, as he faces difficulties with his team, butts heads with his rival-turned-teammate Vincent DuBois, and falls in love with his trainer, a former prima ballerina named Scarlett DuBois, who happens to be his rival\'s sister.', 'striker.jpg', 329, 479, 'romance', 'fiction', '', '2025-02-02 07:23:29', 'true', NULL),
(14, 'King of Sloth', 'Ana Huang', 'anahuang.jpg', 'Cool, intelligent, and ambitious, Sloane Kensington is a high-powered publicist who\'s used to dealing with difficult clients. However, none infuriate—or tempt—her more than a certain billionaire heir, with his stupid dimples and laid-back attitude.', 'kingofsloth.jpg', 279, 415, 'romance', 'fiction', 'best', '2025-02-02 07:23:50', 'true', NULL),
(15, 'Twisted Love', 'Ana Huang ', 'anahuang.jpg', 'a romance novel by Ana Huang about a cold-hearted millionaire and a free-spirited college student who develop an uneasy friendship', 'twistedlove.jpg', 400, 352, 'Romance', 'fiction', 'best', '2025-02-02 07:16:42', 'true', NULL),
(16, 'Smoke, Mirrors and Murder', 'Ann Rule', 'annrule.jpg', 'An ideal family is targeted for death by the least likely enemy, who plotted their demise from behind bars.... A sexual predator hides behind multiple fake identities, eluding police for years while his past victims live in fear that he will hunt them down.', 'smokemirrorandmurder.jpg', 350, 326, 'mystery', 'fiction', '', '2025-02-02 07:21:39', 'true\r\n', NULL),
(17, 'The Little Prince', 'Antoine De Saint-Exupery', 'antonie.jpeg', 'The story is a sort of coming-of-age story about the main character, the Little Prince, who comes to earth from a distant planet. Out of loneliness he has left his own tiny planet, where his only friend is a rose.', 'littleprince.jpg', 89, 99, 'kids', 'kids', '', '2025-02-02 07:24:26', 'true', NULL),
(18, 'Cosmos', 'Carl Sagan', 'carlsagan.jpeg', 'Sagan explores 15 billion years of cosmic evolution and the development of science and civilization. He traces the origins of knowledge and the scientific method, mixing science and philosophy, and speculates about the future of science.', 'cosmos.jpg', 350, 391, 'science', 'non-fiction', '', '2025-02-02 07:24:45', 'true', NULL),
(19, 'Red, White and Royal Blue', 'Casey McQuiston', 'caseymcquistion.jpg', 'Red, White & Royal Blue is an LGBT romance novel by American author Casey McQuiston, originally published on May 14, 2019, by St Martin\'s Griffin. It centers on the character of Alex Claremont-Diaz, a first son of the United States, and his romantic relationship with Prince Henry, a British prince. ', 'redwhite.jpg', 329, 398, 'romance', 'fiction', '', '2025-02-02 07:21:05', 'true', NULL),
(20, 'The Origin of Species', 'Charles Darwin', 'charlesdarwin.avif', 'On the Origin of Species is a work of scientific literature by Charles Darwin that is considered to be the foundation of evolutionary biology. It was published on 24 November 1859.', 'originofspecies.jpg', 350, 493, 'science', 'non-fiction', '', '2025-02-02 07:26:37', 'true\r\n', NULL),
(21, 'Mistress of Spices', 'Chitra Banarjee Divakaruni', 'chitra.jpg', 'In The Mistress of Spices, Divakaruni tells the story of Tilo, a young woman born in another time, in a faraway place, who is trained in the ancient art of spices and ordained as a mistress charged with special powers.', 'the-mistress-of-spices.jpg', 600, 317, 'fantasy', 'fiction', '', '2025-02-02 07:30:13', 'true', NULL),
(22, 'Palace of Illusions', 'Chitra Banarjee Divakaruni', 'chitra.jpg', 'The Palace of Illusions: A Novel is a 2008 novel by Chitra Banerjee Divakaruni, published by Doubleday. The novel is a rendition of the Hindu epic Mahabharata as told from Draupadi\'s viewpoint, namely, that of a woman living in a patriarchal world.\r\n\r\nThe Palace of Illusions traces the princess Panchaali\'s life, beginning with her birth in fire and following her spirited balancing act as a woman with five husbands who have been cheated out of their father\'s kingdom.\r\n', 'poi.jpg', 300, 384, 'fantasy', 'fiction', 'best', '2025-02-03 05:15:54', 'true', NULL),
(23, 'The Forest of Enchantments ', 'Chitra Banarjee Divakaruni', 'chitra.jpg', 'Laced with Sita\'s joys and sorrows, her agony and her triumph, her heartbreak and her resilience,The Forest of Enchantments also invites us into the lives of other women who are misunderstood and relegated to the margins: Kaikeyi, Surpanakha, Mandodari.', 'foe.jpg', 329, 372, 'fantasy', 'fiction', '', '2025-02-03 05:17:41', 'true\r\n', NULL),
(24, 'Verity', 'Colleen Hoover', 'colleenhoover.jpg', 'Lowen Ashleigh is a struggling writer on the brink of financial ruin when she accepts the job offer of a lifetime. Jeremy Crawford, husband of bestselling author Verity Crawford, has hired Lowen to complete the remaining books in a successful series his injured wife is unable to finish.', 'verity.jpg', 199, 244, 'mystery', 'fiction', 'best', '2025-02-02 07:30:27', 'true', NULL),
(25, 'The Da Vinci Code ', 'Dan Brown', 'danbrown.jpg', 'The Da Vinci Code follows symbologist Langdon and cryptologist Sophie Neveu after a murder in the Louvre Museum in Paris entangles them in a dispute between the Priory of Sion and Opus Dei over the possibility of Jesus and Mary Magdalene having had a child together.', 'the-da-vinci-code.jpg', 289, 516, 'mystery', 'fiction', '', '2025-02-02 07:31:21', 'true', NULL),
(26, 'To Die For', 'David Baldacci', 'DavidBaldacci.jpg', 'Travis Devine is back and his time as an Army Ranger will come in very useful on this mission. Devine is asked to fly to Seattle to assist the FBI with a twelve year old girl whose parents died right in front of her.', 'todiefor.jpg', 389, 411, 'mystery', 'fiction', '', '2025-02-02 07:32:28', 'true', NULL),
(27, 'Howl\'s Moving Castle', 'Diana Wynne Jones', 'DianaJones.jpg', 'Sophie Hatter is a pretty average girl whose been left to maintain her family\'s hat shop. However, she gets cursed one day by the Witch of the Waste and is turned into an old woman.', 'movingcastle.jpg', 200, 230, 'fantasy', 'fiction', '', '2025-02-02 07:34:54', 'true', NULL),
(28, 'Wings of Fire', 'Dr. A.P.J Abdul Kalaam', 'abdulkalaam.jpg', 'Wings of Fire is an autobiography by Dr. APJ Abdul Kalam, the 11th President of India. The book is about his life, struggles, and contributions to India\'s missile and space programs. ', 'wings-of-fire.jpg', 299, 320, 'Biographies', 'non-fiction', '', '2025-02-02 07:35:35', 'true', NULL),
(29, 'Charlotte\'s Web', 'E.B.White', 'white.jpg', 'Charlotte\'s Web is a story of friendship, courage, and self-sacrifice. Wilbur is a pig who finds out that he is destined for slaughter. His friend, a spider named Charlotte who lives in the doorway of his pigpen, determines to save him; she accomplishes this by spinning words about him in her web.', 'charlottesweb.jpg', 109, 145, 'kids', 'kids', '', '2025-02-02 09:20:37', 'true', NULL),
(30, 'Dune', 'Frank Herbert', 'frankherbert.jpeg', 'Dune, science fiction novel by American author Frank Herbert, serialized in Analog from 1963 to 1965 and then published in book form later in 1965. Dune follows young nobleman Paul Atreides through adversity to his destiny as a messianic leader on the arid desert planet Arrakis', 'dune.jpg', 450, 526, 'science fiction', 'fiction', '', '2025-02-02 08:28:25', 'true', NULL),
(31, 'The Metamorphosis', 'Franz Kafka', 'franzkafka.jpg', 'The Metamorphosis by Franz Kafka is about a man named Gregor Samsa who becomes an insect. Until this incident, Gregor has worked hard to support his parents and sister. After he can no longer provide for their financial comfort, Gregor discovers that his family can indeed work.', 'metamorphosis.jpg', 159, 296, 'fantasy', 'fiction', 'best', '2025-02-02 08:29:27', 'true', NULL),
(32, 'Gone Girl', 'Gillian Flynn', 'gillianflynn.jpg', 'The book Gone Girl is a novel written by author Gillian Flynn. It is written as a contemporary thriller novel and is first published in June 2012. The novel\'s core mystery stems from an uncertainty about the protagonist, Nick Dunne. Whether Nick killed his wife, Amy Dunne, is the suspense the novel is built up on.', 'gonegirl.jpg', 329, 377, 'mystery', 'fiction', '', '2025-02-02 08:30:19', 'true', NULL),
(33, 'Haunting Adeline', 'H.D. Carlton', 'carlton.jpg', 'Haunting Adeline by H.D. Carlton is a fictional novel about a young writer who inherits a haunted manor and becomes the target of a stalker. ', 'ha.jpg', 350, 602, 'romance', 'fiction', 'best', '2025-02-02 08:30:59', 'true\r\n', NULL),
(34, 'Good Girl\'s Guide to Murder', 'Holly Jackson', 'hollyjackson.jpeg', 'our heroine is Pippa Fitz-Amobi, a high school senior who hopes to be a journalist someday. She lives in a town where, only five years earlier, a high school girl named Andie Bell was murdered. The solution at the time was that Andie\'s boyfriend killed her, then himself.', 'gggtm.jpg', 400, 401, 'mystery', 'fiction', 'best', '2025-02-02 08:31:45', 'true', NULL),
(35, 'A Fellowship of Libarians and Dragons', 'J Penner', 'penner.jpg', 'In the quaint town of Adenashire, Doli Butterbuckle, a people-pleasing sunshine dwarf, is content with her simple tea magic and circle of friends. It\'s true she\'s never quite lived up to family expectations, but life is just fine--until her parents arrive with an inherited dragon egg and a charming gargoyle harboring a secret stroll into her life.  As Doli grapples with her newfound responsibility and discovers a long hidden side of herself, she must face an overbearing family, a sinister plot, and a mischievous dragon that refuses to stay out of trouble.  But with the help of her loyal friends and newfound love, Doli embarks on a heartwarming adventure, revealing that embracing her true self is the most enchanting path of all.', 'tfolad.jpg', 249, 218, 'fantasy', 'fiction', '', '2025-02-02 08:32:40', 'true', NULL),
(36, 'Pride and Prejudice', 'Jane Austen', 'janeausten.jpg', 'Pride and Prejudice follows the turbulent relationship between Elizabeth Bennet, the daughter of a country gentleman, and Fitzwilliam Darcy, a rich aristocratic landowner. They must overcome the titular sins of pride and prejudice in order to fall in love and marry.', 'prideandprejudice.jpg', 349, 450, 'romance', 'fiction', '', '2025-02-02 08:34:06', 'true\r\n', NULL),
(37, 'On the Social Contract', 'Jean Jacques Rousseau', 'jean.jpg', 'Social contract theory says that people live together in society in accordance with an agreement that establishes moral and political rules of behavior. Some people believe that if we live according to a social contract, we can live morally by our own choice and not because a divine being requires it.', 'onsocialcontract.jpg', 250, 326, 'philosophy', 'non-fiction', '', '2025-02-02 08:34:55', 'true', NULL),
(38, 'From Blood and Ash', 'Jennifer Armentrout', 'jennifer.jpg', 'Forsaken by the gods and feared by mortals, a fallen kingdom is rising once more, determined to take back what they believe is theirs through violence and vengeance. And as the shadow of those cursed draws closer, the line between what is forbidden and what is right becomes blurred.', 'bloodandash.jpg', 349, 493, 'fantasy', 'fiction', '', '2025-02-02 08:35:41', 'true', NULL),
(39, 'The Summer I Turned Pretty', 'Jenny Han', 'jennyhan.jpg', 'The Summer I Turned Pretty is a coming-of-age story about love, friendship, and growing up. Belly is a relatable character who is struggling to figure out who she is and what she wants. She is also dealing with the complicated relationships she has with Conrad and Jeremiah.', 'sitp.jpg', 129, 150, 'romance', 'fiction', '', '2025-02-02 08:36:40', 'true', NULL),
(40, 'Harry Potter And The Deathly Hallows', 'JK Rowling', 'jkrowling.jpg', 'The young wizard Harry Potter is about to turn seventeen and therefore lose the protective magic shield his mother\'s sacrifice gave him. He is being escorted to The Burrow by members of the Order of the Phoenix when the group is attacked by Death Eaters, who kill \"Mad-Eye\" Moody and injure George Weasley.\r\n', 'harrypotter.jpg', 450, 522, 'ya', 'fiction', '', '2025-02-02 11:04:54', 'true', NULL),
(41, 'The Fault in our Stars', 'John Green', 'johngreen.jpg', 'The Fault in Our Stars by John Green is a young adult fiction novel that narrates the story of a 16-year-old girl who is diagnosed with cancer. She joins a support group where she meets Augustus, and there is a rollercoaster of emotions throughout this novel as the relationship between Hazel and Augustus develops.', 'thefaultinourstars.jpg', 169, 225, 'ya', 'fiction', '', '2025-02-02 11:04:57', 'true', NULL),
(42, 'Gulliver\'s Travels', 'Jonathan Swift', 'swift.jpg', 'Gulliver\'s Travels is the story of the adventures of Lemuel Gulliver, the narrator and protagonist of the story. Gulliver is a married surgeon from Nottinghamshire, England, who has a taste for traveling. He works as a surgeon on ships and eventually becomes a ship captain.', 'gulliverstravel.jpg', 459, 673, 'picture book', 'kids', 'best', '2025-02-02 08:40:31', 'true', NULL),
(43, 'Dont Believe Everything You Think', 'Joseph Nguyen', 'joseph.jpg', '\'Don\'t Believe Everything You Think\' uncovers the core of psychological suffering and offers insights to effortlessly shape the life you crave. Learn to detach from negativity, embrace love and joy, escape negative thought cycles, and tap into inner wisdom.', 'dbeyt.jpg', 129, 84, 'self help', 'non-fiction', '', '2025-02-02 08:41:41', 'true\r\n', NULL),
(44, 'The Duke and I ', 'Julia Quinn', 'juliaquinn.jpg', 'The Duke and I is a romance set in the Regency era. A young, marriageable lady should be amiable… but not too amiable.', 'duke and I.jpg', 600, 400, 'Romance', 'fiction', '', '2025-02-02 08:42:09', 'true', NULL),
(45, 'The Lies We Tell', 'Kate Anslinger', 'kateanslinger.jpg', 'Haley Tilbury was sixteen years old when she discovered she was adopted. Almost ten years later she comes face to face with Evie Sullivan, the woman she thinks is her biological mother.  When Haley starts dating Dylan Crowe, criminal defense attorney and brother of a prime suspect in an unsolved murder case, she finds herself in a tangled maze of questions that lead her back to her past.', 'the-lies-we-tell.jpg', 250, 217, 'ya', 'fiction', '', '2025-02-02 11:04:43', 'true', NULL),
(46, 'Reign of the Stars and the fire', 'L.J.Andrew', 'andrew.jpg', 'With darkness spreading across the fae isles, the reluctant raven queen seeks the aid of Calista, the storyteller, and unwittingly falls into a dark tale of twisted fates. To save Ari from being lost in a fae sleep, Saga will reach into the past and uncover deadly secrets left behind by her brother, the last fate king.    Both Saga and Ari must unravel the lies of their world if they are to stand a chance at defeating the fiercest enemy yet.    But when their actions will end in the destruction of every kingdom, Saga and Ari must make a choice: risk the lives of those they love, or burn the world to save each other.    Return to the epic, passionate love story of Ari and Saga in the spicy new adult fantasy romance where fae Vikings come to life with heart-stopping battles, dangerous magic, and tantalizing romance.', 'rosaf.jpg', 350, 412, 'fantasy', 'fiction', '', '2025-02-02 08:44:15', 'true', NULL),
(47, 'If You Give A Mouse A Cookie', 'Laura Numeroff', 'lauranumeroff.jpg', 'This story describes a set of events that occurs after a boy gives a mouse a cookie. Once the mouse is given the cookie, he asks for a glass of milk, which ends up leading to a series of additional requests. Each event that occurs makes the mouse want something new, creating a seemingly endless stream of demands.', 'iygamac.jpg', 59, 40, 'kids', 'kids', '', '2025-02-02 08:46:18', 'true', NULL),
(48, 'Broken Path', 'Laura Rise', 'laurarise.jpeg', 'When victims are found mysteriously murdered in the woods with hunting traps, former FBI agent Ivy Pane vows to stop this cruel killer. With her right arm compromised, can she outwit a cunning predator with her sharp mind and resolute spirit? .', 'brokenpath.jpg', 179, 188, 'mystery', 'fiction', '', '2025-02-02 08:47:17', 'true', NULL),
(49, 'Empty Soul', 'Laura Rise', 'laura.jpg', 'LAFD Arson Investigator Bree Noble can smell the difference between a natural fire and arson. Ever since a suspicious fire claimed the lives of her parents, Bree’s life mission has been to stop arsonists—but after a deadly new fire, she may just be up against the case of her life…\r\n\r\n \r\n\r\nBree uncovers a trail of infernos set by a distinct chemical compound and must use her skills and brave the flames of her past to find, and stop, a cold-blooded killer.', 'emptysoul.jpg', 250, 250, 'mystery', 'fiction', '', '2025-02-03 07:34:00', 'true', NULL),
(50, 'In Too Deep', 'Lee Child And Andrew Child', 'leechild.jpg', 'When Rose DuLoe is forced to leave her comfortable city life for a mansion in the middle of nowhere, she feels out of control. Worse, the estate is owned by the man who drives her crazy - but when tensions boil over and they have the hottest hate-sex of her life, she\'s left feeling more confused than ever.    Blake is controlling, arrogant and a player but being stuck together for their own protection means Rose can\'t help but see what\'s been staring her in the face all along.    With a gala to plan and a stalker to catch, can Rose and Blake make it through without wanting to kiss - or kill - each other?', 'itd.jpg', 289, 264, 'romance', 'fiction', '', '2025-02-02 08:49:18', 'true', NULL),
(51, 'Gods, Guns and Missionaries', 'Manu Pillai', 'manupillai.jpg', 'When European missionaries arrived in India in the sixteenth century, they entered a world both fascinating and bewildering. Hinduism, as they saw it, was a pagan mess: a worship of devils and monsters by a people who burned women alive, performed outlandish rites and fed children to crocodiles.', 'ggam.jpg', 600, 718, 'history', 'non-fiction', '', '2025-02-02 08:50:37', 'true', NULL),
(52, 'The Rainbow Fish', 'Marcus Pfister', 'marcuspfister.jpg', 'The Rainbow Fish is a lovely, heart-warming story of sharing and the happiness that sharing can bring yourself and others. It also depicts how difficult sharing can be and the impact that sharing can have on friendships. Rainbow Fish, like many young children, has a difficult time sharing.', 'therainbowfish.jpg', 49, 13, 'kids', 'kids', '', '2025-02-02 08:51:27', 'true', NULL),
(53, 'Goodnight Moon', 'Margaret Wise Brown', 'margaret.jpg', 'The text is a rhyming poem, describing an anthropomorphic bunny\'s bedtime ritual of saying \"good night\" to various inanimate and living objects in the bunny\'s bedroom: a red balloon, a pair of socks, the bunny\'s dollhouse, a bowl of mush, a woman (an older female anthropomorphic rabbit, possibly his mother or an adult .', 'goodnightmoon.jpg', 49, 22, 'kids', 'kids', '', '2025-02-02 08:52:27', 'true', NULL),
(54, 'Album of Dogs', 'Marguerite Henry', 'henry.jpg', 'This artful collection of canine companions from Newbery Medalist Marguerite Henry is majestically illustrated and makes a great gift for dog lovers of all ages.Marguerite Henry may be best known for her stories about horses, but she loved all animals.', 'albumofdogs.jpg', 129, 136, 'picture book', 'kids', '', '2025-02-02 08:53:21', 'true', NULL),
(55, 'The Book Theif', 'Markus Zsak', 'zusak.jpeg', 'The Book Thief is a book about a girl during World War II in Nazi Germany. Her foster parents hide a Jewish man, but this man is forced to leave once attention is drawn to the family. Ultimately the girls\' town is bombed, and her foster parents and best friend are killed.', 'tbt.jpg', 289, 540, 'ya', 'fiction', '', '2025-02-02 11:04:46', 'true', NULL),
(56, 'Being and Time', 'Martin Heidegger', 'martin.jpg', 'Being and Time is the 1927 magnum opus of German philosopher Martin Heidegger and a key document of existentialism. Being and Time had a notable impact on subsequent philosophy, literary theory and many other fields.', 'beingandtime.jpg', 350, 591, 'philosophy', 'non-fiction', '', '2025-02-02 08:54:57', 'true', NULL),
(57, 'The Calculating Stars', 'Mary Robinette Kowal', 'mary.jpg', 'The Calculating Stars by Mary Robinette Kowal starts with a bang! Literally, a giant meteor hits the Earth, completely wiping out the East Coast of the United States. This event begins the process of climate change, which some believe will eventually make the planet unlivable.', 'tcs.jpg', 289, 372, 'science fiction', 'fiction', '', '2025-02-02 08:57:27', 'true', NULL),
(58, 'Why We Sleep', 'Matthew Walker', 'walker.jpg', 'Why We Sleep: The New Science of Sleep and Dreams is a 2017 popular science book about sleep written by Matthew Walker, an English scientist and the director of the Center for Human Sleep Science at the University of California, Berkeley, who specializes in neuroscience and psychology.', 'whywesleep.jpg', 250, 277, 'science', 'non-fiction', '', '2025-02-02 08:58:23', 'true', NULL),
(59, 'Becoming', 'Michelle Obama', 'obama.jpg', 'Becoming Me traces Obama\'s early life growing up on the South Side of Chicago with her parents, Fraser and Marian Robinson, in an upstairs apartment where she got her first piano lessons and learnt to be an independent girl under the nurturing care of her parents.', 'becoming.jpg', 350, 477, 'biographies', 'non-fiction', 'best', '2025-02-02 11:10:31', 'true', NULL),
(60, 'Your Inner Fish', 'Neil Shubin', 'neilshubin.jpeg', 'Based on a best-selling book by paleobiologist Neil Shubin, this scientific adventure story takes viewers from Ethiopia to the Arctic Circle on a hunt for the many ways that our animal ancestors shaped our anatomical destiny', 'innerfish.jpg', 199, 213, 'science', 'non-fiction', '', '2025-02-02 09:00:09', 'true', NULL),
(61, 'The Art of Letting Go', 'Nick Trenton', 'nicktrenton.jpg', 'The Art of Letting Go is a book about how to move beyond pain and negative thoughts to live a more fulfilling life. It offers strategies to help you let go of the past, accept the present, and look forward to the future. ', 'lettinggo.jpg', 129, 141, 'self help', 'non-fiction', 'best', '2025-02-02 09:01:26', 'true', NULL),
(62, 'The Mirror', 'Nora Roberts', 'noraroberts.jpg', '#1 New York Times bestselling author Nora Roberts continues the hauntingly spectacular Lost Bride Trilogy with book two, The Mirror. When Sonya MacTavish inherits the huge Victorian mansion on the coast of Maine, she has no idea that the house is haunted.', 'themirror.jpg', 450, 433, 'science fiction', 'fiction', '', '2025-02-02 09:02:13', 'true', NULL),
(63, 'The Picture of Dorian Gray', 'Oscar Wilde', 'oscarwilde.jpg', 'The Picture of Dorian Gray is the story of a beautiful young man who unknowingly makes a Faustian bargain to remain eternally youthful. Seems like a good idea. Spoiler alert: it isn\'t. Like all deals with the devil, the cost is his soul and the price turns out to be too high.', 'dg.jpg', 319, 432, 'fantasy', 'fiction', '', '2025-02-02 09:03:12', 'true', NULL),
(64, 'Are You My Mother?', 'P.D. Eastman', 'eastman.jpg', 'Are You My Mother? is a story about a hatchling bird. His mother, thinking her egg will stay in her nest where she left it, leaves her egg alone and flies off to find food. The baby bird hatches while the mother is away. The hatchling does not understand where his mother is so he goes to look for her.\r\n', 'areyoumymother.jpg', 59, 67, 'kids', 'kids', '', '2025-02-02 09:04:07', 'true', NULL),
(65, 'The Name of the Wind', 'Patrick Rothfuss', 'patrick.jpg', 'It is revealed that Kote is actually the renowned Kvothe: an unequaled sword fighter, magician, and musician, rumored to have killed a king—earning the title Kingkiller—and caused the present war in which the civilized world is embroiled. Bast is Kvothe\'s assistant and student and a prince of the Fae', 'thenameofthewind.jpg', 450, 619, 'adventure', 'fiction', '', '2025-02-02 09:04:57', 'true', NULL),
(66, 'The Girl on the Train', 'Paula Hawkins', 'paula.jpg', 'The Girl on the Train is a 2015 psychological thriller novel by British author Paula Hawkins that gives narratives from three different women about relationship troubles and, for the main protagonist, alcoholism.', 'tgott.jpg', 199, 261, 'mystery', 'fiction', '', '2025-02-02 09:22:55', 'true', NULL),
(67, 'The Silk Roads', 'Peter Frankopan', 'peter.jpg', 'The Silk Roads: A New History of the World is a 2015 non-fiction book written by English historian Peter Frankopan, a historian at the University of Oxford. A new abridged edition was illustrated by Neil Packer. The full text is divided into 25 chapters. ', 'thesilkroads.jpg', 150, 146, 'history', 'non-fiction', '', '2025-02-02 09:07:57', 'true', NULL),
(68, 'The Republic', 'Plato', 'plato.jpg', 'The Republic is a Socratic dialogue authored by Plato around 375 BC, concerning justice, the order and character of the just city-state, and the just man. It is Plato\'s best-known work, and one of the world\'s most influential works of philosophy and political theory, both intellectually and historically.', 'tr.jpg', 350, 407, 'philosophy', 'non-fiction', '', '2025-02-02 09:07:06', 'true', NULL),
(69, 'Nationalism', 'Rabindranath Tagore', 'rabindranath.jpg', 'Nationalism is a comprehensive exploration of the historical, political, and cultural phenomenon of nationalism. Written by Rabindranath Tagore, a renowned poet and philosopher, this thought-provoking book delves into the complexities and consequences of nationalistic fervor.', 'nationalism.jpg', 129, 65, 'philosophy', 'non-fiction', '', '2025-02-02 09:06:20', 'true', NULL),
(70, 'The Path to Self Love', 'Ruby Dhal', 'ruby.jpg', 'This comprehensive, inspiring book provides strategies for taking a deep dive into issues of self-love and acceptance. On a personal experience writen book can help you to explore your core values and understand how those values affect your everyday life.', 'tptsl.jpg', 229, 267, 'self help', 'non-fiction', '', '2025-02-02 09:08:35', 'true', NULL),
(71, 'The Hating Game', 'Sally Throne', 'sally.jpg', 'Written by Sally Thorne, “The Hating Game” follows Lucy Hutton\'s whirlwind of emotions regarding coworker, and nemesis, Joshua Templeman. Both work as assistants to their respective bosses in a joint publishing house, which requires them to sit across from each other.', 'thg.jpg', 289, 333, 'romance', 'fiction', '', '2025-02-02 09:09:12', 'true', NULL),
(72, 'Audacious Optimism', 'Shanna Adamic', 'shanna.jpeg', 'Audacious Optimism delivers a riveting account of Shanna Adamic\'s journey from a highly successful career as a corporate philanthropist and former professional cheerleader, to surviving a rare and life-threatening brain tumor, to limited mobility and a 4% chance of regaining facial function on her right side, to her complete recovery and developing an unwavering dedication to optimism. This book teaches readers how to rally from within and push through those terrifying moments in life, when you\'ve got it all on the line, and when the odds are looking slim, to find the hope and courage needed to make it through the darkness and out into a life full of wonder and joy.', 'ao.jpg', 789, 217, 'self-help', 'non-fiction', '', '2025-02-02 09:11:29', 'true', NULL),
(73, 'When We Had Forever', 'Shaylin Gandhi', 'gandhi.jpg', 'An emotionally powerful roller coaster of a novel about losing and finding love, perfect for fans of Colleen Hoover and Lucy Score.  Six months after her husband died in a car crash, Mina Drake is still mired in a haze of grief. Reminders of her years with Michael are everywhere, but beneath her heartache lies an even more painful emotion. It’s a guilty suspicion she can hardly admit to anyone, even herself—that her marriage was over long before Michael’s accident.  They were good together once, she’s sure of it, sharing a connection so deep that Mina can’t understand how it unraveled. That is, until a chance discovery in her husband’s office—and the reappearance of Michael’s estranged brother, Grayson, a notorious bad-boy photographer—awakens her to possible answers.', 'wwhf.jpg', 350, 316, 'romance', 'fiction', '', '2025-02-02 09:12:18', 'true', NULL),
(74, 'The Ant And The Grasshopper', 'Sigal Adler', 'sigal.jpg', 'The fable concerns a grasshopper (in the original, a cicada) that has spent the summer singing and dancing while the ant (or ants in some versions) worked to store up food for winter. When winter arrives, the grasshopper finds itself dying of hunger and begs the ant for food.', 'tantgh.jpg', 59, 60, 'picture book', 'kids', '', '2025-02-02 09:13:49', 'true', NULL),
(75, 'The Adventures of Sherlock Holmes', 'Sir Arthur Conan Doyle', 'conan.jpg', 'The Adventures of Sherlock Holmes is a collection of short stories by British writer Arthur Conan Doyle, first published on 14 October 1892. It contains the earliest short stories featuring the consulting detective Sherlock Holmes, which had been published in twelve monthly issues of The Strand Magazine from July 1891 to June 1892. ', 'taosh.jpg', 109, 81, 'adventure', 'fiction', '', '2025-02-02 09:14:59', 'true', NULL),
(76, 'The Hunger Games', 'Suzanne Collins', 'suzanne.jpg', 'The Hunger Games are a series of young adult dystopian novels written by American author Suzanne Collins. The series consists of a trilogy that follows teenage protagonist Katniss Everdeen, with a prequel set 64 years before the original series. ', 'thehungergames.jpg', 319, 297, 'ya', 'fiction', '', '2025-02-02 11:06:01', 'true', NULL),
(77, 'The Bell Jar', 'Sylvia Plath', 'plath.jpg', 'After being rejected for a writing class, Esther must spend the rest of her summer at home with her mother; Esther\'s father died when she was young. She struggles to write a novel and becomes increasingly despondent, making several half-hearted suicide attempts. She ultimately overdoses on sleeping pills but survives.', 'thebelljar.jpg', 149, 192, 'ya', 'fiction', '', '2025-02-02 11:05:58', 'true', NULL),
(78, 'Exhalation', 'Ted Chiang', 'ted.jpg', 'This story is based in a dystopian set-up where air is considered as the source of life. Lungs can be replenished with air at filling stations and a spare set of lungs can be kept aside for emergency. So long as there is enough air to refill, life will continue undeterred.', 'exhalation.jpg', 250, 292, 'science fiction', 'fiction', '', '2025-02-02 09:18:29', 'true', NULL),
(79, 'Divergent', 'Veronica Roth', 'roth.jpg', 'In The New York Times, Susan Dominus stated that Divergent \"explores a more common adolescent anxiety--the painful realization that coming into one\'s own sometimes means leaving family behind ideologically and physically', 'divergent.jpg', 250, 288, 'ya', 'fiction', '', '2025-02-02 11:05:51', 'true', NULL),
(80, 'Steve Jobs', 'Walter Isaacson', 'walter.jpg', 'The author kept this book unfiltered, not glorifying Steve\'s culture of berating employees in public and claiming others\' ideas as his own, among other traits. The book also narrates Steve\'s contribution to the digital revolution and his empowerment of artists with the iPod.', 'stevejobs.jpg', 450, 638, 'biographies', 'non-fiction', '', '2025-02-02 11:10:48', 'true', NULL),
(81, 'Atomic Habits', 'William Dalrymple', 'william.jpg', 'Atomic Habits by James Clear is a comprehensive, practical guide on how to change your habits and get 1% better every day. Using a framework called the Four Laws of Behavior Change, Atomic Habits teaches readers a simple set of rules for creating good habits and breaking bad ones.', 'at.jpg', 550, 685, 'self help', 'non-fiction', 'best', '2025-02-02 09:21:23', 'true', NULL),
(82, 'The Golden Road', 'William Dalrymple', 'william.jpg', 'The Golden Road: How Ancient India Transformed the World is a 2024 history book by William Dalrymple. It discusses the ways in which India\'s ideas and influences spread throughout and shaped Eurasia.', 'tgr.jpg', 550, 685, 'history', 'non-fiction', '', '2025-02-02 09:21:54', 'true', NULL),
(83, 'One Last Stop', 'Casey Mcquiston', 'casey.jpg', 'One Last Stop is a 2021 LGBTQ romance novel written by American author Casey McQuiston. The novel is about a woman named August Landry, a cynical pseudo detective, who finds love in a woman she meets on a subway named Jane Su, a punk butch lesbian from the 1970s who has been misplaced in time and is trapped on the subway.', 'onelaststop.jpg', 350, 432, 'romance', 'fiction', '', '2025-02-04 06:54:20', 'true', NULL),
(84, 'The Pairing', 'Casey Mcquiston', 'casey.jpg', 'The Pairing is a 2024 romance novel by Casey McQuiston published by St. Martin\'s Griffin. The plot follows Theo and Kit, two bisexual exes who happen to be on the same food and wine tour across Europe. To deal with the awkwardness, they bet on who can sleep with the most people on the tour.', 'thepairing.jpg', 745, 432, 'romance', 'fiction', 'best', '2025-02-04 07:00:07', 'true', NULL),
(85, 'The Stranger Beside Me', 'Ann Rule', 'annrule.jpg', 'The Stranger Beside Me is a 1980 autobiographical and biographical true crime book written by Ann Rule about serial killer Ted Bundy, whom she knew personally before and after his arrest for a series of murders. Subsequent revisions of the book were published in 1986, 1989, 2000, 2008, and 2021.', 'stranger.jpg', 400, 480, 'Biographies', 'non-fiction', '', '2025-02-04 07:04:41', 'true', NULL),
(86, 'Letters to Milena', 'Franz Kafka', 'franzkafka', 'Letters to Milena is a book collecting some of Franz Kafka\'s letters to Milena Jesenská from 1920 to 1923. The English translation of the letters states, \"Whereas Kafka generally wrote to Milena in German, most of her letters were in her mother tongue\" of Czech (', 'letterstomilena.jpg', 500, 298, 'Biographies', 'non-fiction', '', '2025-02-04 07:07:33', 'true', NULL),
(87, 'Teenage Juggad', 'Mitra Malani', 'mitra.jpeg', 'Teenage Jugaad by Mitra Malani is a guide for teens navigating 18 key life decisions, from dating to careers. Blending relatable stories with practical advice, it helps young readers make informed choices. Malani, an equestrian and psychology enthusiast, brings diverse insights to empower youth.', 'teenage jugaad.jpg', 179, 225, 'Self-Help', '', '', '2025-02-19 06:47:31', 'true', NULL),
(88, 'God of Small Things', 'Arundhathi Roy', 'roy.jpeg', 'it is a nice book', 'god of small things.jpg', 400, 339, 'Young Adult', '', '', '2025-02-19 06:47:24', 'true', NULL),
(89, 'Crime and Punishment', 'Fyodor Dostoevsky', 'dost.jpeg', 'Crime and Punishment is a novel by the Russian author Fyodor Dostoevsky. It was first published in the literary journal The Russian Messenger in twelve monthly installments during 1866. It was later published in a single volume. ', 'crimeandpunishment.jpeg', 293, 400, 'Mystery', '', '', '2025-02-19 06:47:11', 'true', NULL),
(90, 'The Diary of the Young Girl', 'Anne Frank', 'annefrank.jpg', 'The Diary of a Young Girl, commonly referred to as The Diary of Anne Frank, is a book of the writings from the Dutch-language diary kept by Anne Frank while she was in hiding for two years with her family during the Nazi occupation of the Netherlands.', 'thediaryoftheyounggirl.jpeg', 250, 293, 'biographies', 'non-fiction', '', '2025-02-19 11:41:45', 'true', NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `books`
--
ALTER TABLE `books`
  ADD PRIMARY KEY (`book_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `books`
--
ALTER TABLE `books`
  MODIFY `book_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=91;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `books`
--
ALTER TABLE `books`
  ADD CONSTRAINT `fk_books_authors` FOREIGN KEY (`author_id`) REFERENCES `authors` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
